config/routes.rb
Rails.application.routes.draw do
  get 'users/passwordrecovery', to: 'users#password_recovery', as: :password_recovery
  post 'users/passwordrecovery', to: 'users#set_new_password'
  
  get 'transfers', to: 'users#history_transfer', as: :history_transfer
  
  get 'users/:id/transfer', to: 'users#transfer', as: :transfer
  patch 'set_transfer' => 'users#set_transfer'
  
  get 'users/:id/local', to: 'users#local', as: :local
  post 'users/:id/local', to: 'users#set_local'
  
  get 'users/:id/workshops', to: 'users#workshops', as: :workshop_user
  
  get 'users/:id/register', to: 'users#register', as: :register
  post 'users/:id/register', to: 'users#set_register', as: :set_register
  
  #Rotas de SessionsController
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  
  resources :speakers
  resources :hotels
  resources :rooms
  resources :workshops
  resources :federations
  resources :ejs
  resources :users
  
  root 'sessions#new'
end

app/models/workshop.rb
class Workshop < ApplicationRecord
    mount_uploader :file, FileUploader
  
  belongs_to :speaker
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show, :edit, :update, :destroy]
  before_action :set_speakers, only: [:new, :create, :edit, :update]
  before_action :only_admin

  # GET /workshops
  # GET /workshops.json
  def index
    @workshops = Workshop.all
    @workshops = Workshop.paginate(:page => params[:page], :per_page => 5)
    
    respond_to do |format|
      format.html
      format.xls
    end
  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  # GET /workshops/1/edit
  def edit
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = Workshop.new(workshop_params)

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: 'Workshop was successfully created.' }
        format.json { render :show, status: :created, location: @workshop }
      else
        format.html { render :new }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop.destroy
    respond_to do |format|
      format.html { redirect_to workshops_url, notice: 'Workshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workshop_params
      params.require(:workshop).permit(:name, :start, :finish, :speaker_id, :file)
    end
    
    def set_speakers
      @speakers = Speaker.all
    end
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_form.html.erb
<%= form_with(model: workshop, local: true) do |form| %>
  <% if workshop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>

      <ul>
      <% workshop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :name, id: :workshop_name %>
  </div>
  
  <%= form.label :palestrante %>
  <%= form.select :speaker_id, @speakers.collect { |speaker| [speaker.name,speaker.id] }%><br />

  <div class="field">
    <%= form.label "início" %>
    <%= form.datetime_select :start, id: :workshop_start %>
  </div>

  <div class="field">
    <%= form.label "término" %>
    <%= form.datetime_select :finish, id: :workshop_finish %>
  </div>
  
  <div class="field">
    <%= form.label :arquivos %>
    <%= form.file_field :file, id: :workshop_file %>
  </div>
  
  <div class="actions">
    <%= form.submit "Atualizar Palestra" %>
  </div>
<% end %>

app/views/workshops/edit.html.erb
<% provide(:title, "Editor | ")%>
<div id="data-table">

<h1>Editar Palestra</h1>

<%= render 'form', workshop: @workshop %>

<%= link_to 'Mostrar', @workshop %> |
<%= link_to 'Voltar', workshops_path %>

</div>

app/views/workshops/index.html.erb
<% provide(:title, "Palestras | ")%>
<p id="notice"><%= notice %></p>

<h1>Palestras</h1>

<table id="data-table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Início</th>
      <th>Término</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workshops.each do |workshop| %>
      <tr>
        <td><%= workshop.name %></td>
        <td><%= workshop.start %></td>
        <td><%= workshop.finish %></td>
        <td><%= link_to 'Mostrar', workshop %></td>
        <td><%= link_to 'Editar', edit_workshop_path(workshop) %></td>
        <td><%= link_to 'Destruir', workshop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @workshops %>
<%= link_to 'Nova Palestra', new_workshop_path %>
<br>
<%= link_to "Baixar Tabela", workshops_path(format: "xls") %>

<script>
  $("#data-table").DataTable({});
</script>

app/views/workshops/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Palestras">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Nome</Data></Cell>
        <Cell><Data ss:Type="String">Início</Data></Cell>
        <Cell><Data ss:Type="String">Término</Data></Cell>
      </Row>
    <% @workshops.each do |workshop| %>
      <Row>
        <Cell><Data ss:Type="String"><%= workshop.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= workshop.start %></Data></Cell>
        <Cell><Data ss:Type="String"><%= workshop.finish %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/workshops/new.html.erb
<% provide(:title, "Criador | ")%>
<div id="data-table">

<h1>Nova Palestra</h1>

<%= render 'form', workshop: @workshop %>

<%= link_to 'Voltar', workshops_path %>
</div>

app/views/workshops/show.html.erb
<% provide(:title, "Palestra | ")%>
<div id="data-table">
<p id="notice"><%= notice %></p>

<p><br>
  <strong>Nome:</strong>
  <%= @workshop.name %>
</p><br>

<p>
  <strong>Início das Inscrições:</strong>
  <%= @workshop.start %>
</p><br>

<p>
  <strong>Final das Inscrições:</strong>
  <%= @workshop.finish %>
</p><br>

<%= link_to 'Editar', edit_workshop_path(@workshop) %> |
<%= link_to 'Voltar', workshops_path %>
</div>