config/routes.rb
Rails.application.routes.draw do
  get 'users/passwordrecovery', to: 'users#password_recovery', as: :password_recovery
  post 'users/passwordrecovery', to: 'users#set_new_password'
  
  get 'transfers', to: 'users#history_transfer', as: :history_transfer
  
  get 'users/:id/transfer', to: 'users#transfer', as: :transfer
  patch 'set_transfer' => 'users#set_transfer'
  
  get 'users/:id/local', to: 'users#local', as: :local
  post 'users/:id/local', to: 'users#set_local'
  
  get 'users/:id/workshops', to: 'users#workshops', as: :workshop_user
  
  get 'users/:id/register', to: 'users#register', as: :register
  post 'users/:id/register', to: 'users#set_register', as: :set_register
  
  #Rotas de SessionsController
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  
  resources :speakers
  resources :hotels
  resources :rooms
  resources :workshops
  resources :federations
  resources :ejs
  resources :users
  
  root 'sessions#new'
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :ej
    belongs_to :room, optional: true
    
    has_secure_password
    mount_uploader :profile_photo, ImageUploader
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, length: { in: 10..50}, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
 
    validates :name, length: { in: 2..50} 
    validates :password, length: { in: 4..16, presence: true, allow_nil: true} 
    validate :picture_size
    
    #valida o tamanho da foto
    def picture_size
        if profile_photo.size > 2.megabytes
            error.ad(:profile_photo, "Impossível carregar fotos com mais de 2MB")    
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :set_local, :register, :set_register, :workshops, :transfer, :set_transfer]
  before_action :correct_user, only: [:edit, :update]
  before_action :correct_user_or_admin, only: [:destroy]
  before_action :logged_user, only: [:new, :create]
  before_action :non_logged_user, except: [:new, :create, :password_recovery, :set_new_password]
  before_action :set_ejs, only: [:new, :create, :edit]
  before_action :set_rooms, only: [:local]
  before_action :full, only: [:set_local]
  before_action :only_admin, only: [:index]
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @users = User.paginate(:page => params[:page], :per_page => 5)
    
    respond_to do |format|
      format.html
      format.xls
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @ejs_ordered = Ej.order(count: :desc)
    @p = 1
    
    @total = {}
    @current_total = 0
    @pp = 0
    
    Federation.all.each do |federation|
      
      federation.ejs.each do |ej|
        @current_total = @current_total + ej.count
      end
      
      @total = @total.merge({federation.name => @current_total})
      @current_total = 0
      @pp = @pp + 1
    end
    
    @total = @total.sort_by {|key, value| value }.reverse
    @pp = 1
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    if User.find_by(:email => user_params[:email])
      redirect_to login_path
      return
    end
    
    @user = User.new(user_params)
    
    @ej = @user.ej
    @ej.count = @ej.count + 1
    @ej.save

    respond_to do |format|
      if @user.save
          UserMailer.confirmation(@user).deliver
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    ej = Ej.find(@user.ej_id)
    
    ej.count = ej.count - 1
    ej.save
    
    inscriptions = UserInscriptionWorkshop.where(:user_id => @user.id)
    
    inscriptions.each do |inscription|
      inscription.destroy
    end
    
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def local
    @hotels = Hotel.all
  end
  
  def set_local
    @user.update_attributes(room_id: params[:room_id])
  
    redirect_to @user
  end
  
  def register
    @workshops = Workshop.all
    @inscriptions = UserInscriptionWorkshop.where(:user_id => @user.id) 
  end
  
  def set_register
    if params[:att][:action] == "do"
      inscription = UserInscriptionWorkshop.new
      inscription.user_id = @user.id
      inscription.workshop_id = params[:att][:workshop_id]
      inscription.save
     
    elsif params[:att][:action] == "undo"
      inscription = UserInscriptionWorkshop.find_by(user_id: @user.id, workshop_id: params[:att][:workshop_id])
      inscription.destroy
    end
    @workshop = Workshop.find(params[:att][:workshop_id])
    respond_to do |format|
      format.html{redirect_to register_path(@user)}
      format.js{}
    end
  end
  
  def transfer
  end
  
  def set_transfer
    if User.find_by(:email => user_params[:email])
      receptor = User.find_by(:email => user_params[:email])
    
      temp = @user.room_id
      @user.room_id = nil
      receptor.room_id = temp
      
      @user.save
      receptor.save
      
      transfer = UserTransferUser.new
      transfer.update_attributes(:transfer => @user, :receptor => receptor)
    end
    
    redirect_to user_path(@user)
  end
  
  def history_transfer
    @transfers = UserTransferUser.all
    @transfers = UserTransferUser.paginate(:page => params[:page], :per_page => 5)
  end
  
  def password_recovery
  end
  
  def set_new_password
    if user = User.find_by(email: params[:session][:email])
      user = User.find_by(email: params[:session][:email])
      new_password = user.password_digest[0..5]
      
      user.password = new_password
      user.password_confirmation = new_password
      user.save
      
      UserMailer.password_recovery(user, new_password).deliver
    end
    
    redirect_to login_path
  end
  
  def workshops
    @users = User.paginate(:page => params[:page], :per_page => 5)
    @workshops = []
    inscriptions = UserInscriptionWorkshop.where(:user_id => @user.id) 
    
    inscriptions.each do |inscription|
      @workshops.append(Workshop.find(inscription.workshop_id))
    end
    
    respond_to do |format|
      format.html
      format.xls
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :telephone, :password, :password_confirmation, :profile_photo, :ej_id, :room_id)
    end
    
    def correct_user
        if current_user != @user
            redirect_to user_path(current_user)
        end
    end
    
    def correct_user_or_admin
        if current_user != @user && !current_user.admin
            redirect_to user_path(current_user)
        end
    end
    
    def set_ejs
      @ejs = Ej.all
    end
    
    def set_rooms
      @rooms = Room.all
    end
    
    def full
      @room = Room.find(params[:room_id])
      
      
      if @room.users.count == @room.capacity
      
        flash[:notice] = "Quarto cheio!"
        redirect_to local_path(@user)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <header>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
  
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </header>
  
  <%= form.text_field :name, id: :user_name, :placeholder => "Nome", :class => "nome", :type => "name" %><br>
  <%= form.text_field :email, id: :user_email, :placeholder => "Email", :class => "email", :type => "email" %><br>
  <%= form.password_field :password, id: :user_password, :placeholder => "Senha", :class => "password", :type => "password" %><br>
  <%= form.password_field :password_confirmation, id: :user_password_confirmation, :placeholder => "Confirme sua senha", :class => "password", :type => "password" %><br>

  <% if @user.persisted? %>
    <%= form.text_field :telephone, id: :user_telephone, :placeholder => "Telefone", :class => "nome", :type => "name" %><br>
    <p>Adicionar Foto:</p> <%= form.file_field :profile_photo %><br />
    <%= form.submit "SALVAR" , :class => "button" %>
  <% else %>
    <p class="ej-escolha">Escolha sua EJ:</p><br>
    <%= form.select :ej_id, @ejs.collect { |ej| [ej.name,ej.id] }, {}, {:class => "ej-select" }%><br />
    <%= form.submit "CRIAR CONTA" , :class => "button" %>
  <% end %>
  
<% end %>

app/views/users/_registration.html.erb
<% if !UserInscriptionWorkshop.find_by(user_id: current_user.id, workshop_id: @workshop.id) %>
     <%= link_to 'Escolher', set_register_path(att: {:action => "do", :workshop_id => @workshop.id}), method: :post, id: "registro#{@workshop.id}", class: "btn-palestra", remote: true, authencity_token: true  %>
<% else %>
    <%= link_to 'Sair', set_register_path(att: {:action => "undo", :workshop_id => @workshop.id}), method: :post, id: "registro#{@workshop.id}", class: "btn-palestra", remote: true, authencity_token: true  %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Editor | ")%>

<div class="container-edit">
    <div class="title">Editar</div><br>
    
    <%= render "form", user: @user%>
</div>

app/views/users/history_transfer.html.erb
<% provide(:title, "Transferências | ")%>
<p id="notice"><%= notice %></p>

<h1>Histórico de Transferências</h1>

<table id="data-table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Transmissor</th>
      <th>Receptor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
      <tr>
        <td><%= transfer.id %></td>
        <td><%= transfer.transfer.name %></td>
        <td><%= transfer.receptor.name %></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @transfers %>
<br>
<%= link_to "Baixar Tabela", history_transfer_path(format: "xls") %>

<script>
  $("#data-table").DataTable({});
</script>

app/views/users/history_transfer.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Transferências">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Id</Data></Cell>
        <Cell><Data ss:Type="String">Transmissor</Data></Cell>
        <Cell><Data ss:Type="String">Receptor</Data></Cell>
      </Row>
    <% @transfers.each do |transfer| %>
      <Row>
        <Cell><Data ss:Type="String"><%= transfer.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= transfer.transfer.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= transfer.receptor.name %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/users/index.html.erb
<% provide(:title, "Usuários | ")%>
<p id="notice"><%= notice %></p>

<h1>Usuários</h1>

<table id="data-table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>EJ</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.ej.name %></td>
        <td><%= link_to 'Destruir', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @users %>
<br>
<%= link_to "Baixar Tabela", users_path(format: "xls") %>

<script>
  $("#data-table").DataTable({});
</script>

app/views/users/local.html.erb
<% provide(:title, "Acomodações | ")%>
<section id="acomodacoes">
    <% @hotels.each do |hotel| %>
        <div class="acomodacoes-usuario">
            <%= image_tag hotel.profile_photo_url(:thumb), :class => "img-hotel" if hotel.profile_photo.present? %>            
            <h2 class="nome-usuario"><%= hotel.name %></h2>
            <br>
            <p><%= hotel.content%></p>
            <br>
            <br>
            <br>
            <br>
            <%= form_with(model: @user, local: true) do |form| %>
              Room: <%= form.select :room_id, hotel.rooms.collect { |room| [room.num.to_s + " " + room.hotel.name, room.id] } %><br />
              
              <%= form.submit "Escolher", :class => "btn-hospedar" %>
            <% end %>
        </div>
    <% end %>
</section>

app/views/users/new.html.erb
<% provide(:title, "Novo Usuário | ")%>
<div class="container">
    <img class="logo" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/822789/profile/profile-512.jpg"><br>
    <div class="title">Inscrição</div><br>
    
    <%= render "form" %>
</div>

app/views/users/password_recovery.html.erb
<% provide(:title, "Recuperar Senha | ")%>
<div class="container">
    <img class="logo" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/822789/profile/profile-512.jpg"><br>
    <div class="title">Esqueceu sua senha?</div><br>
    <br>
    <br>
    
    <%= form_for :session do |f| %>
      <%= f.text_field :email, :id => "input", :placeholder => "Digite seu Email", :class => "email" %><br />
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <%= f.submit "ENVIAR", :class => "button" %>
    <% end %>

</div>

app/views/users/set_register.js.erb
$("#registro<%= @workshop.id %>").replaceWith("<%= escape_javascript(render('users/registration')) %>");

app/views/users/show.html.erb
<% provide(:title, "Home | ")%>
<div class="clear">
    
</div>

<section id="user-ranking">
    <div class="usuario-info">
        <%= image_tag (@user.profile_photo_url(:thumb)), :class => "img-usuario" if @user.profile_photo.present?%>
        <h2 class="nome-usuario"><%= current_user.name %></h2>
        <h3 class="ej-usuario"><%= current_user.ej.name %></h3>
        <% if current_user.room.present? %>
          <h3 class="inscrito">INSCRITO</h3>
        <% else %>
          <h3 class="nao-inscrito">NÃO INSCRITO</h3>
        <% end %>
        
        <h3 class="quarto-usuario"><%= current_user.room.num.to_s + " " + current_user.room.hotel.name if current_user.room.present? %></h3>
        
        <h3><%= link_to "Palestras Inscritas", workshop_user_path %></h3>
        
        <p>Faltam:</p>
        <p class="countdown" id="demo"></p>
        <p>para o evento</p>
        
        <h3><%= link_to "Editar Usuário", edit_user_path %></h3>
    </div>

    <div class="ranking">
        <h2>Ranking de EJs</h2>
        <% @position = 1 %>
        <table>
          <thead>
            <tr>
              <th>Posição</th>
              <th>EJ</th>
              <th>Quantidade</th>
              <th colspan="3"></th>
            </tr>
          </thead>
        
          <tbody>
            <% @ejs_ordered.each do |ej| %>
              <tr>
                <td><%= @p %></td>
                <td><%= ej.name %></td>
                <td><%= ej.count.to_s %></td>
                <td></td>
              </tr>
              
              <% @p = @p + 1 %>
            <% end %>
          </tbody>
        </table>
        
        <h2>Ranking de Federações</h2>
        <table>
          <thead>
            <tr>
              <th>Posição</th>
              <th>Federação</th>
              <th>Quantidade</th>
              <th colspan="3"></th>
            </tr>
          </thead>
        
          <tbody>
            <% @total.each do |federation| %>
              <tr>
                <td><%= @pp %></td>
                <td><%= federation[0] %></td>
                <td><%= federation[1].to_s %></td>
                <td></td>
              </tr>
              
              <% @pp = @pp + 1 %>
            <% end %>
          </tbody>
        </table>
    </div>
</section>

app/views/users/transfer.html.erb
<% provide(:title, "Transferência | ")%>
<div class="container-edit">
  <h1>Transferência</h1>
  
  <%= form_for(@user, :url => {:action => "set_transfer", params: {id: @user.id}}) do |form| %>
    <header>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    
          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    </header>
    
    <%= form.text_field :email, id: :receptor_email, :placeholder => "Email para Transferir", :class => "email", :type => "email", :value => "" %><br>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <%= form.submit "TRANSFERIR" , :class => "button" %>
    
  <% end %>
</div>

app/views/users/workshops.html.erb
<% provide(:title, "Palestras | ")%>
<h1>Palestras Inscritas</h1>

  <table id="data-table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Palestrante</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @workshops.each do |workshop| %>
        <tr>
          <td><%= workshop.name %></td>
          <td><%= workshop.speaker.name %></td>
          <td><%= workshop.start %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
<%= will_paginate @users %>

<br>
<%= link_to "Baixar Tabela", workshop_user_path(format: "xls") %>

<script>
  $("#data-table").DataTable({});
</script>

app/views/users/workshops.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Palestras">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Nome</Data></Cell>
        <Cell><Data ss:Type="String">Palestrante</Data></Cell>
      </Row>
    <% @workshops.each do |workshop| %>
      <Row>
        <Cell><Data ss:Type="String"><%= workshop.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= workshop.speaker.name %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>