config/routes.rb
Rails.application.routes.draw do
  get 'users/passwordrecovery', to: 'users#password_recovery', as: :password_recovery
  post 'users/passwordrecovery', to: 'users#set_new_password'
  
  get 'transfers', to: 'users#history_transfer', as: :history_transfer
  
  get 'users/:id/transfer', to: 'users#transfer', as: :transfer
  patch 'set_transfer' => 'users#set_transfer'
  
  get 'users/:id/local', to: 'users#local', as: :local
  post 'users/:id/local', to: 'users#set_local'
  
  get 'users/:id/workshops', to: 'users#workshops', as: :workshop_user
  
  get 'users/:id/register', to: 'users#register', as: :register
  post 'users/:id/register', to: 'users#set_register', as: :set_register
  
  #Rotas de SessionsController
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  
  resources :speakers
  resources :hotels
  resources :rooms
  resources :workshops
  resources :federations
  resources :ejs
  resources :users
  
  root 'sessions#new'
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  has_many :users
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :set_hotels, only: [:new, :create, :edit, :update]
  before_action :only_admin
  
  # GET /rooms
  # GET /rooms.json
  
  def index
    @rooms = Room.all
    @rooms = Room.paginate(:page => params[:page], :per_page => 5)
    
    respond_to do |format|
      format.html
      format.xls
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:num, :capacity, :hotel_id)
    end
    
    def set_hotels
      @hotels = Hotel.all
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Número" %>
    <%= form.number_field :num, id: :room_num %>
  </div>

  <div class="field">
    <%= form.label :capacidade %>
    <%= form.number_field :capacity, id: :room_capacity %>
  </div>
  
  <div class="field">
    Hotel: <%= form.select :hotel_id, @hotels.collect { |hotel| [hotel.name, hotel.id] } %><br />
  </div>

  <div class="actions">
    <%= form.submit "Atualizar Quarto"%>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<% provide(:title, "Editor | ")%>
<div id="data-table">

<h1>Editar Quartos</h1>

<%= render 'form', room: @room %>

<%= link_to 'Mostrar', @room %> |
<%= link_to 'Voltar', rooms_path %>

</div>

app/views/rooms/index.html.erb
<% provide(:title, "Quartos | ")%>
<p id="notice"><%= notice %></p>

<h1>Quartos</h1>

<table id="data-table">
  <thead>
    <tr>
      <th>Número</th>
      <th>Hotel</th>
      <th>Capacidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.num %></td>
        <td><%= room.hotel.name %></td>
        <td><%= room.capacity %></td>
        <td><%= link_to 'Mostrar', room %></td>
        <td><%= link_to 'Editar', edit_room_path(room) %></td>
        <td><%= link_to 'Destruir', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @rooms %>
<%= link_to 'Novo Quarto', new_room_path %>
<br>
<%= link_to "Baixar Tabela", rooms_path(format: "xls") %>

<script>
  $("#data-table").DataTable({});
</script>

app/views/rooms/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Quartos">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Número</Data></Cell>
        <Cell><Data ss:Type="String">Hotel</Data></Cell>
        <Cell><Data ss:Type="String">Capacidade</Data></Cell>
      </Row>
    <% @rooms.each do |room| %>
      <Row>
        <Cell><Data ss:Type="String"><%= room.num.to_s %></Data></Cell>
        <Cell><Data ss:Type="String"><%= room.hotel.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= room.capacity.to_s %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/rooms/new.html.erb
<% provide(:title, "Criador | ")%>
<div id="data-table">

<h1>Novo Quarto</h1>

<%= render 'form', room: @room %>

<%= link_to 'Voltar', rooms_path %>
</div>

app/views/rooms/show.html.erb
<% provide(:title, "Quarto | ")%>
<div id="data-table">
<p id="notice"><%= notice %></p>

<p>
  <strong>Número:</strong>
  <%= @room.num %>
</p><br>

<p>
  <strong>Capacidade:</strong>
  <%= @room.capacity %>
</p><br>

<p>
  <strong>Reservas:</strong>
  <%= @room.users.count %>
</p><br>

<%= link_to 'Editar', edit_room_path(@room) %> |
<%= link_to 'Voltar', rooms_path %>
</div>