config/routes.rb
Rails.application.routes.draw do
  get 'users/passwordrecovery', to: 'users#password_recovery', as: :password_recovery
  post 'users/passwordrecovery', to: 'users#set_new_password'
  
  get 'transfers', to: 'users#history_transfer', as: :history_transfer
  
  get 'users/:id/transfer', to: 'users#transfer', as: :transfer
  patch 'set_transfer' => 'users#set_transfer'
  
  get 'users/:id/local', to: 'users#local', as: :local
  post 'users/:id/local', to: 'users#set_local'
  
  get 'users/:id/workshops', to: 'users#workshops', as: :workshop_user
  
  get 'users/:id/register', to: 'users#register', as: :register
  post 'users/:id/register', to: 'users#set_register', as: :set_register
  
  #Rotas de SessionsController
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  
  resources :speakers
  resources :hotels
  resources :rooms
  resources :workshops
  resources :federations
  resources :ejs
  resources :users
  
  root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ej.rb
class Ej < ApplicationRecord
  belongs_to :federation
  
  has_many :users
end

app/models/federation.rb
class Federation < ApplicationRecord
  
  has_many :ejs, dependent: :destroy
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms
  
  mount_uploader :profile_photo, ImageUploader
  
  def picture_size
        if profile_photo.size > 2.megabytes
            error.ad(:profile_photo, "Impossível carregar fotos com mais de 2MB")    
        end
    end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  has_many :users
end

app/models/speaker.rb
class Speaker < ApplicationRecord
  has_many :workshops
  mount_uploader :profile_photo, ImageUploader
  
  def picture_size
        if profile_photo.size > 2.megabytes
            error.ad(:profile_photo, "Impossível carregar fotos com mais de 2MB")    
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :ej
    belongs_to :room, optional: true
    
    has_secure_password
    mount_uploader :profile_photo, ImageUploader
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, length: { in: 10..50}, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
 
    validates :name, length: { in: 2..50} 
    validates :password, length: { in: 4..16, presence: true, allow_nil: true} 
    validate :picture_size
    
    #valida o tamanho da foto
    def picture_size
        if profile_photo.size > 2.megabytes
            error.ad(:profile_photo, "Impossível carregar fotos com mais de 2MB")    
        end
    end
end

app/models/user_transfer_user.rb
class UserTransferUser < ApplicationRecord
  belongs_to :transfer, class_name: "User", foreign_key: "user1"
  belongs_to :receptor, class_name: "User", foreign_key: "user2"
end

app/models/workshop.rb
class Workshop < ApplicationRecord
    mount_uploader :file, FileUploader
  
  belongs_to :speaker
end

app/controllers/ejs_controller.rb
class EjsController < ApplicationController
  before_action :set_ej, only: [:show, :edit, :update, :destroy]
  before_action :set_federations, only: [:new, :create, :edit, :update]
  before_action :only_admin

  # GET /ejs
  # GET /ejs.json
  def index
    @ejs = Ej.all
    @ejs = Ej.paginate(:page => params[:page], :per_page => 5)
    
    respond_to do |format|
      format.html
      format.xls
    end
  end

  # GET /ejs/1
  # GET /ejs/1.json
  def show
  end

  # GET /ejs/new
  def new
    @ej = Ej.new
  end

  # GET /ejs/1/edit
  def edit
  end

  # POST /ejs
  # POST /ejs.json
  def create
    @ej = Ej.new(ej_params)

    respond_to do |format|
      if @ej.save
        format.html { redirect_to @ej, notice: 'Ej was successfully created.' }
        format.json { render :show, status: :created, location: @ej }
      else
        format.html { render :new }
        format.json { render json: @ej.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ejs/1
  # PATCH/PUT /ejs/1.json
  def update
    respond_to do |format|
      if @ej.update(ej_params)
        format.html { redirect_to @ej, notice: 'Ej was successfully updated.' }
        format.json { render :show, status: :ok, location: @ej }
      else
        format.html { render :edit }
        format.json { render json: @ej.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ejs/1
  # DELETE /ejs/1.json
  def destroy
    @ej.destroy
    respond_to do |format|
      format.html { redirect_to ejs_url, notice: 'Ej was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ej
      @ej = Ej.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ej_params
      params.require(:ej).permit(:name, :federation_id)
    end
    
    def set_federations
      @federations = Federation.all
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :set_hotels, only: [:new, :create, :edit, :update]
  before_action :only_admin
  
  # GET /rooms
  # GET /rooms.json
  
  def index
    @rooms = Room.all
    @rooms = Room.paginate(:page => params[:page], :per_page => 5)
    
    respond_to do |format|
      format.html
      format.xls
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:num, :capacity, :hotel_id)
    end
    
    def set_hotels
      @hotels = Hotel.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ejs_helper.rb
module EjsHelper
end

app/helpers/federations_helper.rb
module FederationsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Se houver alguem logado, retornara o usuario
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  # Se houver alguem logado, retorna true
  def logged_in?
    !current_user.nil?
  end
  
  # Retira o id do usuario logado do cookie de sessao e limpa o current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  #Redirecionar para o perfil do Usuario, caso o mesmo ja esteja logado
  def logged_user
    if logged_in?
    redirect_to user_path(current_user)
    end
  end
  # Redireciona para a pagina de login se o user não estiver logado
  def non_logged_user
    if !logged_in?
    redirect_to login_path
    end
  end
  
  def only_admin
    if !current_user.admin
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %>EFEJ</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !current_page?(login_path) &&  !current_page?(new_user_path) && !current_page?(password_recovery_path) && !current_page?('/')%>
      <header class="menu">
        <% if current_user.admin %>
            <div class="menu-container">
                <a class="menu-logo" href="#"><img class="logo-img" src="#" alt="Gerenciador"></a>
                <nav class="menu-nav">
                    <ul>
                      <li><%= link_to "Usuários", users_path %> </li>
                      <li><%= link_to "EJs", ejs_path %> </li>
                      <li><%= link_to "Federações", federations_path %> </li>
                      <li><%= link_to "Hotéis", hotels_path %></li>
                      <li><%= link_to "Quartos", rooms_path %></li>
                      <li><%= link_to "Palestrantes", speakers_path %></li>
                      <li><%= link_to "Palestras", workshops_path %></li>
                      <li><%= link_to "Transferências", history_transfer_path %> </li>
                    </ul>
                </nav>
            </div>
        <% end %>
        <div class="menu-container">
            <a class="menu-logo" href="#"><img class="logo-img" src="#" alt="Logo"></a>
            <nav class="menu-nav">
                <ul>
                   <li><%= link_to "Home", user_path(current_user) %> </li>
                    <li><%= link_to "Acomodações", local_path(current_user) %></li>
                    <li><%= link_to "Programação", register_path(current_user) %></li>
                    <li><%= link_to "Transferir", transfer_path(current_user) %></li>
                    <li><% if logged_in? %>
                      <%=link_to "Sair", logout_path, method: :delete %></p>
                    <% end %></li>
                </ul>
            </nav>
        </div>
      </header>
    <% end %>
    <% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
    <%= yield %>
  </body>
</html>